sageone:
  client_id: 'YOUR_CLIENT_ID'
  client_secret: 'YOUR_CLIENT_SECRET'
  signing_secret: 'YOUR_SIGNING_SECRET'
  apim_subscription_key: 'YOUR_APIM_SUBSCRIPTION_KEY'
  callback_url: 'YOUR_CALLBACK_URL'
  auth_endpoint: 'http://mysageone.ca.sageone.com/oauth2/auth'
  token_endpoint: 'http://mysageone.ca.sageone.com/oauth2/token'
  base_endpoint: 'https://api.columbus.sage.com/global/sageone'
